### ISSUE TITLE
Keep list of languages up to date and remove hello.cs file

### ISSUE THREAD

**Issue by abhinavk99** [AshOlogn/hello-world#8]
hello.cs is unnecessary because there is already HelloWorld.cs

Also we should keep the list of languages in the README up to date

**Comment by Oceanwall** [comment]
If the name of the file is not HelloWorld.extension, then it should be deleted. Upboat me if you agree.

**Comment by theKidOfArcrania** [comment]
Okay heres what im thinking, having HelloWorld be the prefix for all files is a little bit verbose. I agree we should have a standard naming convention, but preferably something shorter!

**Comment by abhinavk99** [comment]
Closing because I want to clean up my issues list.
